import numpy as np
import pandas as pd
from nlmpy import nlmpy
from scipy.interpolate import BSpline
from scipy.optimize import lsq_linear
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
import os
import time
import pandas as pd
import rasterio as rio
import rioxarray as rxr

# TODO:

    # may need to reconsider how alpha div is determined/alpha raster is used
    # because right now there are still a lot of cells with 0 species niche
    # centers located there, and thus no guarantee that at least 1 species will
    # occur there

    # I wonder if GDM won't capture the patterns until survey is actually cast
    # as proper abundances rather than simple binary pres/abs?? though I think
    # GDM should work just fine with pres/abs...

    # work through numerical artefacts:
        # using normal distribution across the [0,1] interval, so many will
        # extend outside it

        # artefacts caused by the 1-inverse logic approach to determining
        # sigma? is that approach justifiable?

        # need to use gamma to somehow constrain min and max alpha values that
        # occur on the map? (i.e., least and most diverse communities)

        # does ignoring spatial autocorrelation in presence/absence
        # determination create any major problems?

        # does ignoring the chance correlation between environmental layers
        # (e.g., by calculating overall presence prob as the prod of
        # independent presence probs on each axis) create any problems?

        # should max prob presence, even at the cell defining the niche center,
        # be <1.0?

    # thoroughly review ChatGPT-derived I-spline code and improve or replace

    # add sampling schemes

    # add algorithm for change over time


'''
simulate community composition at any or all points in a simulated landscape

input parameters include:
    - landscape dimensions
    - number of environmental layers
    - spatial autocorrelation of each of those layers
    - splines describing relation of compositional turnover to each of those
      layers
    - an α-diversity layer (map of local species richness)
      (defaults to a layer parameterized same as the first environmental layer)
    - γ-diversity (total species count on landscape)
'''

########################
# FUNCTIONS AND CLASSES:
########################
def one_minus_inv_logit(x):
    '''
    returns 1 - inverse logit of x
    '''
    return 1 - (np.exp(x)/(1+np.exp(x)))


def draw_random_survey_points(dims, n):
    '''
    draw a set of random survey points within a raster whose coordinates range
    from 0 to dim-1 in both axes in dims; each point will be in a separate
    pixel, so n must not exceed the number of pixels
    '''
    assert n > 0 and n<= np.prod(dims)
    X, Y = np.meshgrid(range(dims[0]), range(dims[1]))
    xs = X.ravel()
    ys = Y.ravel()
    pts = [*zip(xs, ys)]
    np.random.shuffle(pts)
    idxs = np.random.choice(range(len(pts)), replace=False, size=n)
    # NOTE: add 0.5 to all points, to place them in cell centers
    rand_pts = [tuple(np.array(pts[idx])+0.5) for idx in idxs]
    return rand_pts


def make_I_spline_basis(x,
                        knots,
                        degree,
                       ):
    # TODO: MORE THOROUGHLY REVIEW CODE GENERATED BY CHATGPT
    '''
    NOTE: QUICK I-SPLINE CODE GENERATED BY CHATGPT!
          works for now but not prefect (e.g., sometimes fits spline y values
          above [0, 1] interval). Works to get me moving forward now, but needs
          to be more carefully reviewed and then either integrated or replaced.

    Generate I-spline basis from B-spline basis by integrating.
    '''
    n_bases = len(knots) - degree - 1
    b_splines = [BSpline.basis_element(knots[i:i+degree+2], extrapolate=False) for i in range(n_bases)]
    x_eval = np.linspace(min(x), max(x), 200)
    dx = x_eval[1] - x_eval[0]
    i_splines = np.zeros((len(x_eval), n_bases))
    for i, b in enumerate(b_splines):
        y_b = np.nan_to_num(b(x_eval))
        i_splines[:, i] = np.cumsum(y_b) * dx
        if np.max(i_splines[:, i]) > 0:
            i_splines[:, i] /= np.max(i_splines[:, i])
    return x_eval, i_splines


def make_I_spline(x,
                  y,
                  knots,
                  degree,
                 ):
    '''
    fit I-spline to provided x and y arrays
    '''
    # I-spline basis
    x_eval, i_splines = make_I_spline_basis(x, knots, degree)
    assert np.all((x_eval[1:]-x_eval[:-1])>=0)
    # evaluate basis functions at original x
    X_basis = np.zeros((len(x), i_splines.shape[1]))
    for i in range(i_splines.shape[1]):
        X_basis[:, i] = np.interp(x, x_eval, i_splines[:, i])
    # fit monotonic spline with non-negative least squares
    res = lsq_linear(X_basis, y, bounds=(0, np.inf))
    coefs = res.x
    # predict over x_eval
    y_fit = i_splines @ coefs
    # NOTE: clipping y values to the [0, 1] interval, but not constraining to
    #       vary between 0 and 1 because that would allow no insignificant
    #       relationships (i.e., flat lines)
    y_fit = np.clip(y_fit, a_min=0, a_max=1)
    return x_eval, y_fit


class ISpline:
    '''
    I-Spline class with method for getting its approximate slope at any x value
    '''
    def __init__(self,
                 x,
                 y,
                 i,
                 knots=np.linspace(0, 1, 8),
                 degree=3,
                ):
        self.i = i
        # validate and save input x and y values
        self._input_x = np.array(x)
        self._input_y = np.array(y)
        # check bounds
        assert np.all(self._input_x>=0) and np.all(self._input_x<=1)
        assert np.all(self._input_y>=0) and np.all(self._input_y<=1)
        # fit and validate the I-spline x and y values
        spline_x, spline_y = make_I_spline(x=self._input_x,
                                           y=self._input_y,
                                           knots=knots,
                                           degree=degree,
                                          )
        self.x  = spline_x
        self.y = spline_y
        # placeholders for GDM-fitted values
        self.x_gdm = None
        self.y_gdm = None
        # check bounds and monotonicity
        assert np.all(self.x>=0) and np.all(self.x<=1)
        assert np.all(self.y>=0) and np.all(self.y<=1)
        assert np.all((self.y[1:] - self.y[:-1])>=0)
    def get_approx_slope(self, x):
        '''
        calculate simple local approximation of slope at value x
        '''
        ind = np.argmin(np.abs(self.x - x))
        assert ind>=0 and ind<= len(self.x-1)
        ind_lo, ind_hi = np.clip([ind-1, ind+1], a_min=0, a_max=len(self.x)-1)
        Δx = self.x[ind_hi] - self.x[ind_lo]
        Δy = self.y[ind_hi] - self.y[ind_lo]
        return Δy/Δx
    def add_GDM_fit(self, fitted_spline_x, fitted_spline_y):
        '''
        add attributes to store a GDM-fitted spline
        '''
        self.x_gdm = fitted_spline_x
        self.y_gdm = fitted_spline_y
    def plot(self, ax=None, legend=False):
        '''
        make simple plot of the fitted spline
        '''
        if ax is None:
            fig = plt.figure(figsize=(6, 4))
            ax = fig.add_subplot(1, 1, 1)
        ax.plot(self._input_x,
                self._input_y,
                'or',
                label='monotonic input data',
               )
        ax.plot(self.x, self.y,
                label='Monotonic I-spline Fit',
                linewidth=2,
                color='black'
               )
        if self.x_gdm is not None and self.y_gdm is not None:
            ax.plot(self.x_gdm, self.y_gdm, ':',
                    label='GDM-fitted I-spline',
                    linewidth=2,
                    color='blue',
                    alpha=0.5,
                   )

        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.set_title(f"env. spline {self.i}", size=14)
        if legend:
            ax.legend()
        ax.grid(True)



def create_species(gamma,
                   alpha,
                   env,
                   splines,
                   min_niche_sigma=0.05,
                   max_niche_sigma=0.50,
                   debug=False,
                  ):
    '''
    create a dict of all species' ecological niches
    (i.e., μ and σ values for all environmental layers)
    '''
    # melt alpha raster vals and transform so they sum to 1
    alpha_ravel = alpha.ravel()
    alpha_trans = alpha_ravel/np.sum(alpha_ravel)
    assert np.allclose(np.sum(alpha_trans), 1)
    # melt env rasters' vals too
    env_ravel = [e.ravel() for e in env]
    # use alpha vals to draw all species niche centers
    # (centers will always be one of the env vectors occuring on the landscape)
    mu_inds = np.random.choice(a=range(len(alpha_trans)),
                               size=alpha_trans.shape,
                               replace=True,
                               p=alpha_trans,
                              )
    # make debug plot comparing alpha raster and species' niche center locations
    if debug:
        counts = np.zeros(alpha_trans.shape)
        for ind in mu_inds:
            counts[ind] += 1
        fig_alpha_vs_niche_cents = plt.figure()
        ax = fig_alpha_vs_niche_cents.add_subplot(1,2,1)
        img = ax.imshow(alpha.reshape(alpha.shape),
                        vmin=0,
                        vmax=1,
                       )
        plt.colorbar(img)
        ax.set_title('alpha rast')
        ax = fig_alpha_vs_niche_cents.add_subplot(1,2,2)
        img = ax.imshow(counts.reshape(alpha.shape),
                        vmin=0,
                        vmax = np.max(counts),
                       )
        plt.colorbar(img)
        ax.set_title('rast of species niche center locs')
        fig_alpha_vs_niche_cents.suptitle('from create_species() fn:')
        fig_alpha_vs_niche_cents.show()
    spp_mus = [[e[i] for e in env_ravel] for i in mu_inds]
    # use spline slope at each μ to draw each σ
    # (Bush et al. 2018 calculate niche width as 3.09/slope,
    # where 3.09 is the ecological distance at which two communities are
    # expected to have 95% dissimilarity (because 1-(1/exp(3.09))=0.954);
    # I think they're dealing with standardized values, whereas we're dealing
    # with values constrained to [0, 1] and we want our niche widths expressed
    # in those terms;
    # TODO: in lieu of a better solution that I should come up with later I'm
    #       just jamming in a simple function (1-inv_logit) to bound sigmas
    #       between min and max values
    spp = {}
    for sp, mus in zip(range(gamma), spp_mus):
        niche = []
        for i, mu in enumerate(mus):
            slope = splines[i].get_approx_slope(mu)
            sigma = one_minus_inv_logit(slope)
            sigma = np.clip(sigma, a_min=min_niche_sigma, a_max=max_niche_sigma)
            niche.append((mu, sigma))
        spp[sp] = niche
    return spp


def do_survey(env,
              spp,
              i,
              j,
              max_prob_pres=1.0,
              debug=False,
             ):
    '''
    use the list of environmental layers provided and the dict of species
    and their niches to survey species composition at grid cell i,j
    '''
    # list to store all species present
    survey = []
    # get environmental values at point grid cell i,j
    # NOTE: points sit at cell centers, so int() converts to their cell indices
    env_vals = np.array([e[int(i), int(j)] for e in env])
    # decide whether each species is present at the grid cell
    for sp, niche in spp.items():
        # get arrays of niche centers and niche widths
        mus = np.array([n[0] for n in niche])
        sigmas = np.array([n[1] for n in niche])
        # construct covariance matrix (NOTE: without covariance between layers!)
        covar = np.zeros([len(mus)]*2)
        covar[np.diag_indices_from(covar)] = sigmas
        # get probability of presence using the cumulative distribution
        # function of the multivariate normal described by the species' niche
        # distributions on all axes (modeled as the probability of drawing
        # from within the species' multivariate normal niche space
        # a series of environmental values equally extreme as or more extreme
        # than the environmental values observed as the survey position)
        # NOTE: calculating and then subtracting difference between survey
        #       location's environmental values and multivariate niche center,
        #       then subtracting that from the niche center in the CDF
        #       calculation, thus getting the probability of a value being
        #       that far below the niche center; then multiplying by two to
        #       get the two-tailed probability of a value as extreme or more so)
        diffs = np.abs(env_vals-mus)
        distr = multivariate_normal(mean=mus, cov=covar, allow_singular=False)
        prob = 2 * distr.cdf(x=mus-diffs)
        assert 0 <= prob <= 1
        # determine presence as a Bernoulli draw on that probability
        # NOTE: ... treating all layers as independent, even though
        #       in reality we could actually fold in cross-layer
        #       correlation to account for chance non-independence between
        #       environmental axes...)
        # NOTE: ... we also ignore spatial autocorrelation of presence in real
        #       species by ignoring any information about whether or not the
        #       species has been determined present in proximal locations...
        if debug:
            print('\n============')
            print(f"\n\tENV: {env_vals}")
            print(f"\n\tNICHE CENTER: {mus}")
            print(f"\n\tNICHE COVAR: {covar}")
            print(f"\n\tPROB: {prob}")
        if np.random.binomial(1, prob):
            survey.append(sp)
    return survey


def prep_GDM_input_data(gamma,
                        surveys,
                        survey_points,
                        env,
                        site_survey_filename='site_survey.csv',
                        env_rast_filename='env_rast.tif',
                       ):
    '''
    prep a set of files to input into a basic R script for running a GDM model
    '''
    # create and save 'site-survey' table
    # (sites in rows, species in columns)
    n_spp = gamma
    n_sites = len(surveys)
    # NOTE: add 3 to include a site column and x and y columns
    add_cols = 3
    site_surv_mat = np.zeros((n_sites, n_spp+add_cols))
    # NOTE: add site column
    site_surv_mat[:, 0] = [*range(len(surveys))]
    for i, survey in enumerate(surveys):
        # NOTE: add x and y columns (points are expressed as (i, j) matrix
        #       indices, so flip them express as (x, y) geographic coordinates
        pt = survey_points[i]
        site_surv_mat[i, 1] = pt[1]
        site_surv_mat[i, 2] = pt[0]
        for j in survey:
            site_surv_mat[i, j+add_cols] = 1
    site_surv_df = pd.DataFrame(site_surv_mat)
    site_surv_df.columns = ['site', 'x', 'y'] + [f'spp{i}' for i in range(gamma)]
    site_surv_df.to_csv(site_survey_filename, index=False)
    # create and save environmental raster
    stack = np.stack(env)
    ydim, xdim = stack.shape[1], stack.shape[2]
    n_bands = stack.shape[0]
    dtype = stack.dtype
    crs = 'EPSG:3857' # just a stand-in projected EPSG, to avoid CRS issues
    transform = rio.transform.from_origin(0, ydim, 1, 1) # top-left corner
    with rio.open(env_rast_filename,
                  'w',
                  driver='GTiff',
                  height=ydim,
                  width=xdim,
                  count=n_bands,
                  dtype=dtype,
                  crs=crs,
                  transform=transform) as dst:
        for n in range(n_bands):
            dst.write(stack[n], n + 1)
    print("\nGDM INPUTS SAVED TO DISK.\n")


def run_GDM(gamma,
            surveys,
            survey_points,
            env,
            site_survey_filename='site_survey.csv',
            env_rast_filename='env_rast.tif',
            spline_filename='GDM_splines.csv',
            pca_rast_filename='GDM_env_rast_PCA.tif',
            ):
    '''
    prep GDM data, save to disk, execute R script to run GDM, then read in and
    return results
    '''
    # prep and save GDM input data
    prep_GDM_input_data(gamma=gamma,
                        surveys=surveys,
                        survey_points=survey_points,
                        env=env,
                        site_survey_filename=site_survey_filename,
                        env_rast_filename=env_rast_filename,
                       )
    # run R script
    R_cmd = (f"Rscript --vanilla run_gdm.r {site_survey_filename} "
             f"{env_rast_filename} {spline_filename} {pca_rast_filename}")
    os.system(R_cmd)
    # read and return results
    splines = pd.read_csv(spline_filename)
    pca_rast = rxr.open_rasterio(pca_rast_filename)
    return splines, pca_rast


def draw_sample(survey,
                scheme,
                efforts,
                rel_abunds,
                obs_probs,
               ):
    '''
    TODO: WRITE ME
    draw sample from given survey using the given sampling scheme and its args,
    including:
        *efforts*: measures of effort (per site; used to extract y-values from
                   a rarefaction curve)
        *rel_abunds*: relative abundances (per species; used to extract species
                      from a rarefaction curve result)
        *obs_probs*: observation probabilities (per species; used to update
                     species results from the rarefaction curve to account for
                     uneven likelihoods of detection)
    '''
    print("OTHER SAMPLING SCHEMES NOT YET IMPLEMENTED! TRY AGAIN.")
    return

def run_sim(env,
            splines,
            alpha,
            gamma,
            survey_points,
            min_niche_sigma=0.05,
            max_niche_sigma=0.50,
            spp_rel_abund=None,
            spp_observ_prob=None,
            sampling_schemes=['all'],
            site_survey_filename='site_survey.csv',
            env_rast_filename='env_rast.tif',
            spline_filename='GDM_splines.csv',
            pca_rast_filename='GDM_env_rast_PCA.tif',
            debug=False,
           ):
    # handle sampling-scheme arguments
    assert len(sampling_schemes) > 0
    for scheme in sampling_schemes:
        assert scheme in ['all',
                          'random',
                          'rel_abund_weighted',
                          'observ_prob_biased',
                         ]
    if 'rel_abund_weighted' in sampling_schemes:
        assert spp_rel_abund is not None
        assert len(spp_rel_abund) == gamma
    if 'observ_prob_biased' in sampling_schemes:
        assert spp_observ_prob is not None
        assert len(spp_observ_prob) == gamma
    # create all species
    print(f"\n\nCREATING SPECIES...\n\n")
    spp = create_species(gamma=gamma,
                         alpha=alpha,
                         env=env,
                         splines=splines,
                         min_niche_sigma=min_niche_sigma,
                         max_niche_sigma=max_niche_sigma,
                         debug=debug,
                        )

    # create the full survey at each point
    print(f"\n\nDOING SURVEYS...\n\n")
    surveys = [do_survey(env, spp, i, j, debug=debug) for i, j in survey_points]

    # create samples for each sampling scheme
    print(f"\n\nDRAWING SAMPLES...\n\n")
    samples = {}
    for scheme in sampling_schemes:
        if scheme == 'all':
            samples[scheme] = surveys
        else:
            samples = draw_sample(surveys, scheme)
            return

    # run GDM and return results
    print(f"\n\nRUNNING GDM...\n\n")
    splines, pca_rast = run_GDM(gamma,
                                surveys,
                                survey_points,
                                env,
                                site_survey_filename=site_survey_filename,
                                env_rast_filename=env_rast_filename,
                                spline_filename=spline_filename,
                                pca_rast_filename=pca_rast_filename,
                               )
    return spp, surveys, samples, splines, pca_rast


class Sim:
    '''
    overall class for the simulation
    '''
    def __init__(self,
                 env,
                 splines,
                 alpha,
                 gamma,
                 survey_points,
                 debug=False,
                 timeit=True,
                ):
        self._debug = debug
        self.env = env
        self.splines = splines
        self.alpha = alpha
        self.gamma = gamma
        self.points = survey_points
        # run and save the simulation
        if timeit:
            start = time.time()
        (spp,
         surveys,
         samples,
         gdm_splines,
         gdm_pca_rast) = run_sim(env=ENV,
                                 splines=SPLINES,
                                 alpha=ALPHA,
                                 gamma=GAMMA,
                                 survey_points=POINTS,
                                 debug=self._debug,
                                )
        if timeit:
            stop = time.time()
            self._runtime_sec = stop-start
            print((f"\n\n\tsimulation ran in {np.round(self._runtime_sec, 1)} "
                   "seconds.\n\n"))
        self.spp = spp
        self.surveys = surveys
        self.samples = samples
        self.gdm_splines = gdm_splines
        self.gdm_pca_rast = gdm_pca_rast


    def plot(self,
             scatter_survey_points=True,
             save=True,
             env_cmaps=['Reds', 'Greens', 'Blues'],
            ):
        '''
        plot the results of a simulation
        '''
        fig = plt.figure(figsize=(16,16))
        gs = fig.add_gridspec(80, 100)

        # plot environment rasters
        axwidth = int(100/len(self.env))-1
        for i, e in enumerate(self.env):
            ax = fig.add_subplot(gs[:20,
                                    (i*axwidth)+(i*1):((i+1)*axwidth)+((i+1)*1)])
            img = ax.imshow(e, vmin=0, vmax=1, cmap=env_cmaps[i])
            plt.colorbar(img)
            # add survey points
            if scatter_survey_points:
                for point in self.points:
                    ax.scatter(point[0],
                               point[1],
                               color='white',
                               edgecolor='black',
                               alpha=0.8,
                               s=24,
                              )
            ax.set_title(f"env. variable {i}", size=14)

        # plot their splines
        for i, spline in enumerate(self.splines):
            spline.add_GDM_fit(self.gdm_splines[f"x.env_rast_{i+1}"],
                               self.gdm_splines[f"y.env_rast_{i+1}"],
                              )
            ax = fig.add_subplot(gs[25:40,
                                    (i*axwidth)+(i*1):((i+1)*axwidth)+((i+1)*1)])
            spline.plot(ax=ax,
                       legend=i==(len(self.env)-1),
                       )

        # plot input alpha raster and actual alpha values at surveyed cells
        ax = fig.add_subplot(gs[50:, :30])
        ax.imshow(self.alpha, vmin=0, vmax=1)
        ax.set_title('input α-diversity raster (scaled [0,1])', size=14)
        ax = fig.add_subplot(gs[50:, 35:65])
        survey_len_arr = np.ones(self.env[0].shape)*np.nan
        for pt, survey in zip(self.points, self.surveys):
            survey_len_arr[int(pt[0]), int(pt[1])] = len(survey)
        survey_lengths = [len(survey) for survey in self.surveys]
        ax.imshow(survey_len_arr,
                  vmin=min(survey_lengths),
                  vmax=max(survey_lengths),
                 )
        ax.set_title('α-diversity at survey sites', size=14)

        # plot PCA rast from GDM transform
        ax = fig.add_subplot(gs[50:, 70:])
        self.gdm_pca_rast.plot.imshow(ax=ax)
        # add survey points
        if scatter_survey_points:
            for point in self.points:
                ax.scatter(point[0],
                           point[1],
                           color='white',
                           edgecolor='black',
                           alpha=0.8,
                           s=24,
                          )
        ax.set_xlabel('')
        ax.set_ylabel('')
        ax.set_title('top 3 PCs from GDM transform')

        # format plot and save
        if save:
            fig.subplots_adjust(hspace=25,
                                wspace=25,
                               )
            fig.show()
            fig.savefig('comm_sim_res.png',
                        dpi=500,
                       )

    def plot_expec_vs_obser_distr(self,
                                  i,
                                  ax_expec=None,
                                  ax_obser=None,
                                  cmap='viridis',
                                 ):
        '''
        plot both the expected and observed distribution of species i
        '''
        assert ((ax_expec is None and ax_obser is None) or
                (ax_expec is not None and ax_obser is not None)), ("axes "
                                "must be provided either for both the "
                                "expected and observed distribution plots "
                                "or for neither.")
        # get species' niche
        niche = self.spp[i]
        # calculate map of expected distribution
        expec = np.zeros(self.env[0].shape)
        for i, e in enumerate(self.env):
            # TODO: calculate and display this as a probability rather than a
            #       simple thresholded binary! for now, thresholded at 1 std
            expec = expec + (np.abs(e-niche[i][0]) <= (1*niche[i][1]))
        expec = (expec==3).astype(np.int16)
        # calculate map of all pixels where species is observed
        # (setting pixels without surveys to NaNs)
        obser = np.zeros(self.env[0].shape)
        for pt, survey in zip(self.points, self.surveys):
            if i in survey:
                obser[int(pt[0]), int(pt[1])] = 1
        for i in range(self.env[0].shape[0]):
            for j in range(self.env[0].shape[1]):
                if (i+0.5, j+0.5) not in self.points:
                    obser[i, j] = np.nan
        # plot both
        show_fig = False
        if ax_expec is None and ax_obser is None:
            fig = plt.figure()
            ax_expec = fig.add_subplot(1,2,1)
            ax_obser = fig.add_subplot(1,2,2)
            show_fig = True
        ax_expec.imshow(expec,
                        cmap=cmap,
                        vmin=0,
                        vmax=1,
                       )
        ax_expec.set_title(f'expected distribution for species {i}')
        ax_obser.imshow(obser,
                         cmap=cmap,
                         vmin=0,
                         vmax=1,
                        )
        ax_obser.set_title(f'observed distribution for species {i}')
        if show_fig:
            fig.show()



####################
# SET PARAMS AND RUN
####################
# behavioral params
DEBUG = True
TIMEIT = True
PLOT_IT = True

SEED = 2
if SEED is not None:
    np.random.seed(SEED)

# landscape params
DIMS = (50, 50)
ENV_H = (1, 1, 1)
ENV = [nlmpy.mpd(nRow=DIMS[0], nCol=DIMS[1], h=h) for h in ENV_H]

# splines
spline_vals = ([[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
                [0.0, 0.05, 0.1, 0.7, 0.8, 0.85, 0.87, 0.9, 0.91, 0.99, 1.0]],
               [[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
                [0.0, 0.04, 0.08, 0.19, 0.29, 0.39, 0.52, 0.66, 0.71, 0.89, 1.0]],
               [[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
                [0.2, 0.24, 0.28, 0.30, 0.33, 0.36, 0.39, 0.40, 0.41, 0.42, 0.43]],
              )
KNOTS = np.linspace(0, 1, 8)
DEGREE = 3
SPLINES = [ISpline(x=v[0],
                   y=v[1],
                   i=i,
                   knots=KNOTS,
                   degree=DEGREE) for i, v in enumerate(spline_vals)]

# 'inventory' diversities (a la Whittaker)
# TODO: how to constrain min and max alpha values vis-a-vis gamma??
ALPHA = None
if ALPHA is None:
    ALPHA = nlmpy.mpd(nRow=DIMS[0], nCol=DIMS[1], h=ENV_H[0])
else:
    assert isinstance(ALPHA, np.ndarray)
GAMMA=10000

# points to collect full surveys and samples at
N_POINTS = None
if N_POINTS is None:
    N_POINTS = np.prod(DIMS)
POINTS = draw_random_survey_points(DIMS, N_POINTS)

sim = Sim(env=ENV,
          splines=SPLINES,
          alpha=ALPHA,
          gamma=GAMMA,
          survey_points=POINTS,
          debug=DEBUG,
          timeit=TIMEIT,
         )

# plot and save results
if PLOT_IT:
    sim.plot(scatter_survey_points=False,
             save=True,
            )
    # plot expected vs. observed distribution for random species
    sp = 0
    sim.plot_expec_vs_obser_distr(i=sp,
                                  cmap='viridis',
                                 )

